import type { Metadata } from "next";
import { Sanchez, Geist_Mono } from "next/font/google";
// import "./globals.css";
import "./globals.css";
import Providers from "@/components/providers";
import { TooltipProvider } from "@/components/ui/tooltip";
import Navbar from "@/components/navbar";
import { Chatbot } from "@/components/chatbot";

const sanchez = Sanchez({
  variable: "--font-serif",
  subsets: ["latin"],
  weight: "400",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sanchez.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Navbar /> */}
        <TooltipProvider>
          <Providers>{children}</Providers>
        </TooltipProvider>
        <Chatbot />
      </body>
    </html>
  );
}
